
package com.webservice.wsdl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HelloService", targetNamespace = "http://server.demo.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HelloService {


    /**
     * 
     * @param userId
     * @return
     *     returns com.webservice.wsdl.User
     */
    @WebMethod
    @WebResult(name = "UserObject", targetNamespace = "")
    @RequestWrapper(localName = "getUserByName", targetNamespace = "http://server.demo.com/", className = "com.webservice.wsdl.GetUserByName")
    @ResponseWrapper(localName = "getUserByNameResponse", targetNamespace = "http://server.demo.com/", className = "com.webservice.wsdl.GetUserByNameResponse")
    @Action(input = "http://server.demo.com/HelloService/getUserByNameRequest", output = "http://server.demo.com/HelloService/getUserByNameResponse")
    public User getUserByName(
        @WebParam(name = "userId", targetNamespace = "")
        int userId);

}
