
package com.webservice.wsdl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "UserService", targetNamespace = "http://user.spring.cxf.demo.com/")
@XmlSeeAlso({
})
public interface UserService {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAgeById", targetNamespace = "http://user.spring.cxf.demo.com/", className = "com.webservice.wsdl.GetAgeById")
    @ResponseWrapper(localName = "getAgeByIdResponse", targetNamespace = "http://user.spring.cxf.demo.com/", className = "com.webservice.wsdl.GetAgeByIdResponse")
    public String getAgeById(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

}
